{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "contextmine.fullname" . }}-postgres
  labels:
    {{- include "contextmine.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "contextmine.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
