apiVersion: v1
kind: Service
metadata:
  name: {{ include "contextmine.fullname" . }}-prefect
  labels:
    {{- include "contextmine.prefect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prefect.service.type }}
  ports:
    - port: {{ .Values.prefect.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "contextmine.prefect.selectorLabels" . | nindent 4 }}
